// <auto-generated />
using System;
using AnVatCanTho.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnVatCanTho.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240505022721_SeedingDB")]
    partial class SeedingDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnVatCanTho.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("District_Name");

                    b.Property<string>("NoAndStreet")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("NoAndStreet");

                    b.Property<int?>("SnackBarId")
                        .HasColumnType("int")
                        .HasColumnName("SnackBar_Id");

                    b.Property<string>("WardName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ward_Name");

                    b.HasKey("Id");

                    b.HasIndex("WardName", "DistrictName");

                    b.HasIndex(new[] { "Id" }, "ADDRESS_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "DistrictName", "WardName" }, "AddressBelongToWard_FK");

                    b.HasIndex(new[] { "CustomerId" }, "CustomerHasAddress_FK");

                    b.HasIndex(new[] { "SnackBarId" }, "SnackBarHasAddress_FK");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DistrictName = "Ninh Kiều",
                            NoAndStreet = "3/2",
                            WardName = "Xuân Khánh"
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            DistrictName = "Ninh Kiều",
                            NoAndStreet = "3/2",
                            WardName = "Xuân Khánh"
                        },
                        new
                        {
                            Id = 3,
                            DistrictName = "Cái Răng",
                            NoAndStreet = "Lý Thái Tổ",
                            SnackBarId = 1,
                            WardName = "Lê Bình"
                        },
                        new
                        {
                            Id = 4,
                            DistrictName = "Cái Răng",
                            NoAndStreet = "Trần Văn Trà",
                            SnackBarId = 2,
                            WardName = "Tân Phú"
                        },
                        new
                        {
                            Id = 5,
                            DistrictName = "Ninh Kiều",
                            NoAndStreet = "87 Phạm Ngũ Lão",
                            SnackBarId = 3,
                            WardName = "Xuân Khánh"
                        },
                        new
                        {
                            Id = 6,
                            DistrictName = "Ninh Kiều",
                            NoAndStreet = "8 - 10, Nguyễn Cư Trinh",
                            SnackBarId = 4,
                            WardName = "An Cư"
                        },
                        new
                        {
                            Id = 7,
                            DistrictName = "Ninh Kiều",
                            NoAndStreet = "45 Lê Lợi",
                            SnackBarId = 5,
                            WardName = "Xuân Khánh"
                        });
                });

            modelBuilder.Entity("AnVatCanTho.Models.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Avatar")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("no-avatar.jpg")
                        .HasColumnName("Avatar");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("City");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Display_Name");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Password");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("Tel")
                        .IsFixedLength();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "ADMINISTRATOR_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "RoleId" }, "AdministratorHasRole_FK");

                    b.ToTable("Administrators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "NA",
                            DisplayName = "Admin",
                            Dob = new DateTime(2024, 5, 5, 9, 27, 18, 993, DateTimeKind.Local).AddTicks(4400),
                            Email = "admin@site.com",
                            Password = "$2a$11$t0XnMZk58p6iLifYBvTKs.Y7ExZN9WbLpfZfInPqKbl1cczLFPZ1K",
                            RoleId = 1,
                            Tel = "NA",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AnVatCanTho.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Address");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("Order_Id");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "BILL_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "OrderId" }, "BillOfOrder_FK");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    b.Property<int?>("LikeQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("LikeQuantity");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<int>("SnackBarId")
                        .HasColumnType("int")
                        .HasColumnName("SnackBar_Id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "SnackBarId");

                    b.HasIndex(new[] { "Id" }, "COMMENT_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "SnackBarId", "ProductId" }, "CommentOfProduct_FK");

                    b.HasIndex(new[] { "CustomerId" }, "CustomerHasComment_FK");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Ngon nha",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            ProductId = 1,
                            SnackBarId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "10 điểm",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            ProductId = 2,
                            SnackBarId = 2
                        },
                        new
                        {
                            Id = 5,
                            Content = "Cũng ngon",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            ProductId = 5,
                            SnackBarId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Hơi bị ngon luôn",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            ProductId = 3,
                            SnackBarId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Món này ăn hơi bị dính",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            ProductId = 4,
                            SnackBarId = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Gà giòn rụm luôn",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            ProductId = 6,
                            SnackBarId = 2
                        },
                        new
                        {
                            Id = 7,
                            Content = "Tuyệt vời",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            ProductId = 7,
                            SnackBarId = 2
                        },
                        new
                        {
                            Id = 8,
                            Content = "Nice",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            ProductId = 8,
                            SnackBarId = 2
                        });
                });

            modelBuilder.Entity("AnVatCanTho.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Avatar")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("no-avatar.jpg")
                        .HasColumnName("Avatar");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Display_Name");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Password");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("Tel")
                        .IsFixedLength();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "CUSTOMER_PK")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "user1.jpg",
                            DisplayName = "NVA",
                            Dob = new DateTime(2024, 5, 5, 9, 27, 18, 807, DateTimeKind.Local).AddTicks(7987),
                            Email = "nva@gmail.com",
                            Password = "$2a$11$BFYqoq7CX6qpIBzlwgTljeCq/BWSvRphSzj5FP3srC4ySupWTWVMm",
                            Tel = "0123456789",
                            Username = "Nguyễn Văn A"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "user2.jpg",
                            DisplayName = "NVB",
                            Dob = new DateTime(2024, 5, 5, 9, 27, 18, 993, DateTimeKind.Local).AddTicks(3938),
                            Email = "nvb@gmail.com",
                            Password = "$2a$11$X6bVdxS1j.B0sr9Fs.vGweuIygqAtKtLBq1Vm2iK6.yIkS9tyq6Di",
                            Tel = "0223456789",
                            Username = "Nguyễn Văn B"
                        });
                });

            modelBuilder.Entity("AnVatCanTho.Models.District", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Name");

                    b.HasIndex(new[] { "Name" }, "DISTRICT_PK")
                        .IsUnique();

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Name = "Ninh Kiều"
                        },
                        new
                        {
                            Name = "Cái Răng"
                        });
                });

            modelBuilder.Entity("AnVatCanTho.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Address");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CustomerId" }, "CustomerHasOrders_FK");

                    b.HasIndex(new[] { "Id" }, "ORDER_PK")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AnVatCanTho.Models.OrderDetail", b =>
                {
                    b.Property<int>("SnackBarId")
                        .HasColumnType("int")
                        .HasColumnName("SnackBar_Id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("Order_Id");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.HasKey("SnackBarId", "ProductId", "OrderId");

                    b.HasIndex("ProductId", "SnackBarId");

                    b.HasIndex(new[] { "OrderId" }, "OrderDetailOfOrder_FK");

                    b.HasIndex(new[] { "SnackBarId", "ProductId" }, "OrderDetailOfProduct_FK");

                    b.ToTable("Order_Details", (string)null);
                });

            modelBuilder.Entity("AnVatCanTho.Models.Product", b =>
                {
                    b.Property<int>("SnackBarId")
                        .HasColumnType("int")
                        .HasColumnName("SnackBar_Id");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Description");

                    b.Property<string>("Ingredient")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Ingredient");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("ProductCategory_Id");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("Stock");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int")
                        .HasColumnName("UnitPrice");

                    b.HasKey("SnackBarId", "Id");

                    b.HasIndex(new[] { "SnackBarId", "Id" }, "PRODUCT_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "ProductCategoryId" }, "ProductOfProductCategory_FK");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            SnackBarId = 2,
                            Id = 2,
                            Description = "Khoai tây chiên là một món ăn phổ biến trên khắp thế giới, được làm từ khoai tây cắt thành dạng que hoặc thanh, sau đó chiên giòn trong dầu. Khoai tây chiên có bề mặt giòn vàng, bên trong mềm mịn, và thường được ăn kèm với sốt cà chua, sốt mayonnaise, hoặc sốt bơ.",
                            Ingredient = "NA",
                            Name = "Khoai tây chiên",
                            ProductCategoryId = 3,
                            Stock = 1,
                            UnitPrice = 15
                        },
                        new
                        {
                            SnackBarId = 1,
                            Id = 1,
                            Description = "Sinh tố bơ là một đồ uống mát lạnh và bổ dưỡng, được làm từ quả bơ chín mọng, sữa tươi hoặc sữa dừa, đường hoặc mật ong, và một chút đá xay nhuyễn. Đây là một lựa chọn tuyệt vời cho những người yêu thích hương vị độc đáo và chất dinh dưỡng của quả bơ. Sinh tố bơ có màu xanh đậm tự nhiên, với hương thơm béo ngậy của quả bơ kết hợp với sự ngọt ngào của sữa và đường.",
                            Ingredient = "NA",
                            Name = "Sinh tố bơ",
                            ProductCategoryId = 2,
                            Stock = 1,
                            UnitPrice = 15
                        },
                        new
                        {
                            SnackBarId = 2,
                            Id = 6,
                            Description = "Gà rán là một món ăn phổ biến trên toàn thế giới, được biết đến với bề mặt ngoài giòn vàng và thịt gà mềm mịn bên trong. Món gà này thường được chế biến bằng cách ngâm trong một hỗn hợp gia vị, sau đó được chiên hoặc nướng cho đến khi thịt chín và bề mặt trở nên giòn và vàng ươm. Gà rán có hương vị đậm đà, béo ngậy từ dầu và gia vị, cùng với vị ngọt tự nhiên của thịt gà.",
                            Ingredient = "NA",
                            Name = "Gà rán",
                            ProductCategoryId = 3,
                            Stock = 1,
                            UnitPrice = 20
                        },
                        new
                        {
                            SnackBarId = 1,
                            Id = 5,
                            Description = "Trà đào cam sả là một đồ uống tươi mát và sảng khoái, kết hợp giữa hương vị ngọt ngào của đào, chua nhẹ của cam, và hương thơm dễ chịu của sả. Món này thường được làm từ trà đen hoặc trà xanh pha loãng kèm theo nước ép đào, nước cam tươi và một ít nước ép sả.",
                            Ingredient = "NA",
                            Name = "Trà đào cam sả",
                            ProductCategoryId = 1,
                            Stock = 1,
                            UnitPrice = 15
                        },
                        new
                        {
                            SnackBarId = 1,
                            Id = 3,
                            Description = "Gỏi cuốn, hay còn gọi là spring roll, là một món ăn truyền thống của Việt Nam, được biết đến với vị ngon, hương thơm, và sự tươi mát. Món này thường được làm từ các nguyên liệu tự nhiên và giàu dinh dưỡng như thịt gà hoặc tôm, rau sống, và các loại rau củ khác nhau, được cuốn trong một tờ bánh tráng mềm mịn và mỏng như giấy.",
                            Ingredient = "NA",
                            Name = "Gỏi cuốn",
                            ProductCategoryId = 4,
                            Stock = 1,
                            UnitPrice = 10
                        },
                        new
                        {
                            SnackBarId = 1,
                            Id = 4,
                            Description = "Món chân gà sốt Thái là một món ăn hấp dẫn và đậm đà, kết hợp giữa sự ngọt của sốt Thái và độ giòn của chân gà. Món này thường được chế biến bằng cách chiên hoặc nướng chân gà cho đến khi chúng giòn vàng, sau đó được tẩm sốt Thái thơm ngon.",
                            Ingredient = "NA",
                            Name = "Chân gà sốt thái",
                            ProductCategoryId = 3,
                            Stock = 1,
                            UnitPrice = 30
                        },
                        new
                        {
                            SnackBarId = 2,
                            Id = 7,
                            Description = "Trà chanh giã tay là một đồ uống tươi mát và sảng khoái, được làm từ trà đen hoặc trà xanh pha loãng kèm với chanh và đường, được giã tay hoặc lắc đều để hòa quện hương vị. Đây là một món uống phổ biến, đặc biệt vào mùa hè, khi hương vị chua cay và ngọt ngào của trà chanh giã tay mang lại cảm giác sảng khoái và giải khát.",
                            Ingredient = "NA",
                            Name = "Trà chanh giã tay",
                            ProductCategoryId = 1,
                            Stock = 1,
                            UnitPrice = 20
                        },
                        new
                        {
                            SnackBarId = 2,
                            Id = 8,
                            Description = "Trà mãng cầu là một loại đồ uống tươi mát và bổ dưỡng, được làm từ lá mãng cầu tươi hoặc lá mãng cầu khô, kết hợp với nước sôi và đường hoặc mật ong để tạo ra một hương vị độc đáo và thơm ngon. Món này thường được thưởng thức nóng hoặc lạnh, tùy thuộc vào sở thích cá nhân.",
                            Ingredient = "NA",
                            Name = "Trà mãng cầu",
                            ProductCategoryId = 1,
                            Stock = 1,
                            UnitPrice = 20
                        },
                        new
                        {
                            SnackBarId = 3,
                            Id = 9,
                            Description = "Da heo chiên giòn là một món ăn phổ biến trong ẩm thực đường phố Việt Nam, được yêu thích bởi độ giòn rụm và hương vị đặc trưng. Đây là món ăn vặt hoặc có thể dùng làm món khai vị trong các bữa ăn.",
                            Ingredient = "NA",
                            Name = "Da heo chiên giòn",
                            ProductCategoryId = 3,
                            Stock = 1,
                            UnitPrice = 20
                        },
                        new
                        {
                            SnackBarId = 3,
                            Id = 10,
                            Description = "Dừa tắc là một món đồ uống đặc sắc và đầy hấp dẫn của Việt Nam, đặc biệt phổ biến ở miền Nam. Món này kết hợp hương vị béo ngậy của nước dừa tươi với vị chua ngọt của tắc (một loại quả giống quýt hay cam), tạo nên một hương vị độc đáo và sảng khoái.",
                            Ingredient = "NA",
                            Name = "Dừa tắc",
                            ProductCategoryId = 1,
                            Stock = 1,
                            UnitPrice = 15
                        },
                        new
                        {
                            SnackBarId = 4,
                            Id = 11,
                            Description = "Bánh tráng cuộn là một món ăn đường phố phổ biến ở Việt Nam, đặc biệt là ở các tỉnh miền Trung và miền Nam. Món này gồm những lá bánh tráng mỏng được cuộn với một hỗn hợp đa dạng của các nguyên liệu như thịt, rau sống, trứng, và đôi khi là các loại đồ ăn vặt khác như xúc xích, chả, hoặc thậm chí là bánh mì.",
                            Ingredient = "NA",
                            Name = "Bánh tráng cuộn",
                            ProductCategoryId = 3,
                            Stock = 1,
                            UnitPrice = 20
                        },
                        new
                        {
                            SnackBarId = 4,
                            Id = 12,
                            Description = "Bánh tráng trộn là một món ăn vặt rất phổ biến ở Việt Nam, đặc biệt là trong giới trẻ. Món này là sự kết hợp của bánh tráng (lá bánh dẻo mỏng làm từ bột gạo), cùng với một loạt các nguyên liệu đa dạng, mang lại hương vị đặc trưng và thú vị.",
                            Ingredient = "NA",
                            Name = "Bánh tráng trộn",
                            ProductCategoryId = 3,
                            Stock = 1,
                            UnitPrice = 20
                        },
                        new
                        {
                            SnackBarId = 4,
                            Id = 13,
                            Description = "Sinh tố xoài là một trong những loại sinh tố yêu thích ở các nước nhiệt đới, nơi xoài luôn tươi ngon và dồi dào. Món này kết hợp vị ngọt tự nhiên và béo ngậy của xoài chín với sự mát lạnh của đá xay, tạo nên một thức uống giải khát hoàn hảo cho những ngày hè nóng bức.",
                            Ingredient = "NA",
                            Name = "Sinh tố xoài",
                            ProductCategoryId = 2,
                            Stock = 1,
                            UnitPrice = 15
                        },
                        new
                        {
                            SnackBarId = 5,
                            Id = 14,
                            Description = "Gỏi đu đủ là một món salad truyền thống của Việt Nam, đặc biệt phổ biến ở miền Nam. Món này được làm từ đu đủ xanh bào sợi, kết hợp với các nguyên liệu tươi ngon khác như tôm, thịt heo, và rau thơm, rắc lên trên là lạc rang giòn. Gỏi đu đủ được nhiều người yêu thích không chỉ vì hương vị đặc trưng mà còn vì tính giải nhiệt, phù hợp với thời tiết nóng ẩm.",
                            Ingredient = "NA",
                            Name = "Gỏi đu đủ",
                            ProductCategoryId = 3,
                            Stock = 1,
                            UnitPrice = 20
                        },
                        new
                        {
                            SnackBarId = 5,
                            Id = 15,
                            Description = "Cá viên chiên là một món ăn vặt phổ biến và ngon miệng, thường được thưởng thức ở nhiều nơi trên thế giới. Đây là một món ăn dễ làm, với các viên cá được chế biến từ thịt cá tươi ngon, được trộn với gia vị và hình thành thành hình viên tròn hoặc hình que trước khi được chiên giòn.",
                            Ingredient = "NA",
                            Name = "Cá viên chiên",
                            ProductCategoryId = 3,
                            Stock = 1,
                            UnitPrice = 20
                        },
                        new
                        {
                            SnackBarId = 5,
                            Id = 16,
                            Description = "Nước mía là một thức uống truyền thống và rất phổ biến trong nhiều nước trên thế giới, đặc biệt là ở các quốc gia nhiệt đới. Món này được làm từ nước cốt mía tươi ngon, được ép từ cây mía và thường được phục vụ lạnh hoặc có đá.",
                            Ingredient = "NA",
                            Name = "Nước mía",
                            ProductCategoryId = 1,
                            Stock = 1,
                            UnitPrice = 15
                        });
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductType_Id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "PRODUCT_CATEGORY_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "ProductTypeId" }, "ProductCategoryOfProductType_FK");

                    b.ToTable("Product_Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Description = "Description",
                            Name = "Sinh tố",
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 1,
                            Description = "Description",
                            Name = "Trà",
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description",
                            Name = "Thức ăn nhanh",
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description",
                            Name = "Thức ăn lành mạnh",
                            ProductTypeId = 2
                        });
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductImage", b =>
                {
                    b.Property<string>("PathName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Path_Name");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<int>("SnackBarId")
                        .HasColumnType("int")
                        .HasColumnName("SnackBar_Id");

                    b.HasKey("PathName");

                    b.HasIndex("ProductId", "SnackBarId");

                    b.HasIndex(new[] { "PathName" }, "PRODUCT_IMAGE_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "SnackBarId", "ProductId" }, "ProductHasImage_FK");

                    b.ToTable("Product_Images", (string)null);

                    b.HasData(
                        new
                        {
                            PathName = "MBGvAbfLEI-khoai-tay-chien-01.jpg",
                            ProductId = 2,
                            SnackBarId = 2
                        },
                        new
                        {
                            PathName = "18Arx7CbQe-sinh-to-bo-01.jpg",
                            ProductId = 1,
                            SnackBarId = 1
                        },
                        new
                        {
                            PathName = "tra-dao-cam-sa.jpg",
                            ProductId = 5,
                            SnackBarId = 1
                        },
                        new
                        {
                            PathName = "goi-cuon.jpg",
                            ProductId = 3,
                            SnackBarId = 1
                        },
                        new
                        {
                            PathName = "chan-ga-sot-thai.jpg",
                            ProductId = 4,
                            SnackBarId = 1
                        },
                        new
                        {
                            PathName = "Wneqo25aPU-ga-ran-01.jpg",
                            ProductId = 6,
                            SnackBarId = 2
                        },
                        new
                        {
                            PathName = "tra-chanh-gia-tay.jpg",
                            ProductId = 7,
                            SnackBarId = 2
                        },
                        new
                        {
                            PathName = "Tra-Mang-Cau.png",
                            ProductId = 8,
                            SnackBarId = 2
                        },
                        new
                        {
                            PathName = "da-heo-chien-gion.jpg",
                            ProductId = 9,
                            SnackBarId = 3
                        },
                        new
                        {
                            PathName = "dua-tac.jpg",
                            ProductId = 10,
                            SnackBarId = 3
                        },
                        new
                        {
                            PathName = "banh-trang-cuon.jpg",
                            ProductId = 11,
                            SnackBarId = 4
                        },
                        new
                        {
                            PathName = "banh-trang-tron.jpg",
                            ProductId = 12,
                            SnackBarId = 4
                        },
                        new
                        {
                            PathName = "sinh-to-xoai.jpg",
                            ProductId = 13,
                            SnackBarId = 4
                        },
                        new
                        {
                            PathName = "goi-du-du.jpg",
                            ProductId = 14,
                            SnackBarId = 5
                        },
                        new
                        {
                            PathName = "ca-vien-chien.jpg",
                            ProductId = 15,
                            SnackBarId = 5
                        },
                        new
                        {
                            PathName = "nuoc-mia.jpg",
                            ProductId = 16,
                            SnackBarId = 5
                        });
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "PRODUCT_TYPE_PK")
                        .IsUnique();

                    b.ToTable("Product_Types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Thức uống"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Thức ăn"
                        });
                });

            modelBuilder.Entity("AnVatCanTho.Models.Rating", b =>
                {
                    b.Property<int>("SnackBarId")
                        .HasColumnType("int")
                        .HasColumnName("SnackBar_Id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    b.Property<double>("Star")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0)
                        .HasColumnName("Star");

                    b.HasKey("SnackBarId", "ProductId", "CustomerId");

                    b.HasIndex(new[] { "CustomerId" }, "DetailRatingOfCustomer_FK");

                    b.HasIndex(new[] { "ProductId", "SnackBarId" }, "DetailRatingofProduct_FK");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            SnackBarId = 1,
                            ProductId = 1,
                            CustomerId = 1,
                            Star = 3.0
                        },
                        new
                        {
                            SnackBarId = 2,
                            ProductId = 2,
                            CustomerId = 2,
                            Star = 4.0
                        },
                        new
                        {
                            SnackBarId = 1,
                            ProductId = 5,
                            CustomerId = 1,
                            Star = 4.0
                        },
                        new
                        {
                            SnackBarId = 1,
                            ProductId = 3,
                            CustomerId = 1,
                            Star = 3.0
                        },
                        new
                        {
                            SnackBarId = 1,
                            ProductId = 4,
                            CustomerId = 1,
                            Star = 5.0
                        },
                        new
                        {
                            SnackBarId = 2,
                            ProductId = 6,
                            CustomerId = 2,
                            Star = 4.0
                        },
                        new
                        {
                            SnackBarId = 2,
                            ProductId = 7,
                            CustomerId = 2,
                            Star = 3.0
                        },
                        new
                        {
                            SnackBarId = 2,
                            ProductId = 8,
                            CustomerId = 2,
                            Star = 5.0
                        });
                });

            modelBuilder.Entity("AnVatCanTho.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Name");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Permission");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "ROLE_PK")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator",
                            Permission = "all"
                        });
                });

            modelBuilder.Entity("AnVatCanTho.Models.SnackBar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Avatar")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("no-avatar.jpg")
                        .HasColumnName("Avatar");

                    b.Property<string>("CoverImage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("no-image.jpg")
                        .HasColumnName("CoverImage");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Display_Name");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Password");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("Tel")
                        .IsFixedLength();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "SNACK_BAR_PK")
                        .IsUnique();

                    b.ToTable("Snack_Bars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "avt-quan-ghien.jpg",
                            Description = "Ghiền là quán ăn vặt Cần Thơ nổi tiếng với những món ăn như: Trà sữa, trà chanh, sinh tố, tàu hũ, khoai tây lắc, bánh tráng trộn… Đây cũng là quán ăn được nhiều du khách ghé thăm khi du lịch Cần Thơ. Sự đa dạng của thực đơn quán kèm với mức giá phải chăng sẽ giúp bạn thỏa sức ăn uống mà không phải lo về chi phí. ",
                            DisplayName = "Quán Ghiền",
                            Dob = new DateTime(2024, 5, 5, 9, 27, 19, 359, DateTimeKind.Local).AddTicks(1100),
                            Email = "snackbar1@site.com",
                            Password = "$2a$11$zMON6JQtYubQ3k.9vHTHseaK54mbgk/qhMNAFfr3M0buQeOaNdbZC",
                            Tel = "0312345678",
                            Username = "snackbar1"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "avt-quan-hoi-do.jpg",
                            Description = "Một lựa chọn ăn vặt bến Ninh Kiều thú vị đó chính là quán Hồi Đó. Không gian quán ở đây được thiết kế theo phong cách thập niên 80 bởi vậy khi đến đây, bạn sẽ có một cảm giác quen thuộc. Ngoài ra, hầu hết đồ dùng, bàn ghế, chén đũa cũng được lựa chọn mang hơi hướng xưa cũ tạo cho du khách những cảm nhận khác lạ. ",
                            DisplayName = "Quán Hồi Đó",
                            Dob = new DateTime(2024, 5, 5, 9, 27, 19, 542, DateTimeKind.Local).AddTicks(2638),
                            Email = "snackbar2@site.com",
                            Password = "$2a$11$889lS.q5CfbUlmptV9dR/.9Qbp39JUEQx7v.93Kx1lklfSZ3kF8HK",
                            Tel = "0312345678",
                            Username = "snackbar2"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "avt-quan-di-lan.jpg",
                            Description = "Da heo chiên giòn là một trong những món ăn vặt ở Cần Thơ được nhiều khách hàng yêu thích, đặc biệt là các bạn trẻ. Tại quán dì Lan, bạn không những được ăn món da heo đặc trưng mà còn có thể gọi thêm nhiều món khác như: Xôi chiên thập cẩm, dừa tắc… Điều làm nên sự khác biệt ở món da heo tại quán đó chính là hầu hết nguyên liệu đều được chủ quán tự làm, đảm bảo vệ sinh, mức giá thành cũng rất phù hợp với học sinh, sinh viên. ",
                            DisplayName = "Da heo chiên giòn Dì Lan",
                            Dob = new DateTime(2024, 5, 5, 9, 27, 19, 762, DateTimeKind.Local).AddTicks(7898),
                            Email = "snackbar3@site.com",
                            Password = "$2a$11$RGnhfaAFV97Guec2Dac5wO2H.2QNDF4KngLQj0K/OvYFDad0CzDuq",
                            Tel = "0312345678",
                            Username = "snackbar3"
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "avt-quan-co-huong.jpg",
                            Description = "Bánh tráng là món ăn vặt quen thuộc của rất nhiều vùng miền khác nhau. Quán bánh tráng cô Hưng là quán ăn vặt Cần Thơ có tên tuổi lâu đời nhất, những món ăn tại đây cũng được chế biến theo hương vị rất đặc trưng. Một vài món ăn hấp dẫn bạn nên thử khi ghé thăm địa điểm này đó chính là: Bánh tráng cuộn sốt mayonnaise, bánh tráng trộn, các loại gỏi,… ",
                            DisplayName = "Quán bánh tráng cô Hưng",
                            Dob = new DateTime(2024, 5, 5, 9, 27, 19, 934, DateTimeKind.Local).AddTicks(8814),
                            Email = "snackbar4@site.com",
                            Password = "$2a$11$6A1YLp39SQZhyNOiVLYuRufu.rfDleJ9gRB6pIJ7gZOFW7EHOn0HW",
                            Tel = "0312345678",
                            Username = "snackbar4"
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "avt-quan-gao-dua.jpg",
                            Description = "Nếu bạn đang tìm kiếm một quán ăn vặt ngon, rẻ ở Cần Thơ thì Gáo Dừa sẽ là một lựa chọn thú vị mà bạn nên tham khảo. Ưu điểm của quán này đó chính là không gian khá thoáng đãng, nhân viên phục vụ hết sức thân thiện. ",
                            DisplayName = "Quán ăn vặt Gáo Dừa Cần Thơ",
                            Dob = new DateTime(2024, 5, 5, 9, 27, 20, 98, DateTimeKind.Local).AddTicks(6777),
                            Email = "snackbar5@site.com",
                            Password = "$2a$11$vVWMnVvvd9/1KOfGLwTvLufQNuI2J59DfcCyDqcpyQJaBz456GMUS",
                            Tel = "0312345678",
                            Username = "snackbar5"
                        });
                });

            modelBuilder.Entity("AnVatCanTho.Models.Ward", b =>
                {
                    b.Property<string>("DistrictName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("District_Name");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("DistrictName", "Name");

                    b.HasIndex(new[] { "DistrictName", "Name" }, "WARD_PK")
                        .IsUnique();

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            DistrictName = "Ninh Kiều",
                            Name = "Xuân Khánh"
                        },
                        new
                        {
                            DistrictName = "Ninh Kiều",
                            Name = "An Cư"
                        },
                        new
                        {
                            DistrictName = "Cái Răng",
                            Name = "Lê Bình"
                        },
                        new
                        {
                            DistrictName = "Cái Răng",
                            Name = "Tân Phú"
                        });
                });

            modelBuilder.Entity("AnVatCanTho.Models.Address", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId");

                    b.HasOne("AnVatCanTho.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.SnackBar", "SnackBar")
                        .WithMany("Addresses")
                        .HasForeignKey("SnackBarId");

                    b.HasOne("AnVatCanTho.Models.Ward", "Ward")
                        .WithMany("Addresses")
                        .HasForeignKey("WardName", "DistrictName")
                        .HasPrincipalKey("Name", "DistrictName");

                    b.Navigation("Customer");

                    b.Navigation("District");

                    b.Navigation("SnackBar");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Administrator", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Role", "Role")
                        .WithMany("Administrators")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Bill", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Order", "Order")
                        .WithMany("Bills")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Comment", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Customer", "Customer")
                        .WithMany("Comments")
                        .HasForeignKey("CustomerId");

                    b.HasOne("AnVatCanTho.Models.SnackBar", "SnackBar")
                        .WithMany()
                        .HasForeignKey("SnackBarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId", "SnackBarId")
                        .HasPrincipalKey("Id", "SnackBarId");

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("SnackBar");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Order", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AnVatCanTho.Models.OrderDetail", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.SnackBar", "SnackBar")
                        .WithMany()
                        .HasForeignKey("SnackBarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId", "SnackBarId")
                        .HasPrincipalKey("Id", "SnackBarId");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("SnackBar");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Product", b =>
                {
                    b.HasOne("AnVatCanTho.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.SnackBar", "SnackBar")
                        .WithMany("Products")
                        .HasForeignKey("SnackBarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("SnackBar");
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductCategory", b =>
                {
                    b.HasOne("AnVatCanTho.Models.ProductType", "ProductType")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductImage", b =>
                {
                    b.HasOne("AnVatCanTho.Models.SnackBar", "SnackBar")
                        .WithMany()
                        .HasForeignKey("SnackBarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId", "SnackBarId")
                        .HasPrincipalKey("Id", "SnackBarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SnackBar");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Rating", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Customer", "Customer")
                        .WithMany("Ratings")
                        .HasForeignKey("CustomerId");

                    b.HasOne("AnVatCanTho.Models.SnackBar", "SnackBar")
                        .WithMany()
                        .HasForeignKey("SnackBarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.Product", "Product")
                        .WithMany("Ratings")
                        .HasForeignKey("ProductId", "SnackBarId")
                        .HasPrincipalKey("Id", "SnackBarId");

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("SnackBar");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Ward", b =>
                {
                    b.HasOne("AnVatCanTho.Models.District", "District")
                        .WithMany("Wards")
                        .HasForeignKey("DistrictName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Comments");

                    b.Navigation("Orders");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("AnVatCanTho.Models.District", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Order", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductType", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Role", b =>
                {
                    b.Navigation("Administrators");
                });

            modelBuilder.Entity("AnVatCanTho.Models.SnackBar", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Ward", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
