// <auto-generated />
using System;
using AnVatCanTho.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnVatCanTho.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240327104205_InitDataBase")]
    partial class InitDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnVatCanTho.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DistrictWardName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("District_Name");

                    b.Property<string>("NoAndStreet")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("NoAndStreet");

                    b.Property<int>("SnackBarId")
                        .HasColumnType("int")
                        .HasColumnName("SnackBar_Id");

                    b.Property<string>("WardName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ward_Name");

                    b.HasKey("Id");

                    b.HasIndex("DistrictName");

                    b.HasIndex("WardName", "DistrictWardName");

                    b.HasIndex(new[] { "Id" }, "ADDRESS_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "DistrictWardName", "WardName" }, "AddressBelongToWard_FK");

                    b.HasIndex(new[] { "CustomerId" }, "CustomerHasAddress_FK");

                    b.HasIndex(new[] { "SnackBarId" }, "SnackBarHasAddress_FK");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Avatar")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Avatar");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("City");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Display_Name");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Password");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("Tel")
                        .IsFixedLength();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "ADMINISTRATOR_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "RoleId" }, "AdministratorHasRole_FK");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Address");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("Order_Id");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "BILL_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "OrderId" }, "BillOfOrder_FK");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Content");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    b.Property<int?>("LikeQuantity")
                        .HasColumnType("int")
                        .HasColumnName("LikeQuantity");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<int>("SnackBarId")
                        .HasColumnType("int")
                        .HasColumnName("SnackBar_Id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "SnackBarId");

                    b.HasIndex(new[] { "Id" }, "COMMENT_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "SnackBarId", "ProductId" }, "CommentOfProduct_FK");

                    b.HasIndex(new[] { "CustomerId" }, "CustomerHasComment_FK");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Avatar")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Avatar");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Display_Name");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Password");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("Tel")
                        .IsFixedLength();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "CUSTOMER_PK")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AnVatCanTho.Models.District", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Name");

                    b.HasIndex(new[] { "Name" }, "DISTRICT_PK")
                        .IsUnique();

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Address");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CustomerId" }, "CustomerHasOrders_FK");

                    b.HasIndex(new[] { "Id" }, "ORDER_PK")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AnVatCanTho.Models.OrderDetail", b =>
                {
                    b.Property<int>("SnackBarId")
                        .HasColumnType("int")
                        .HasColumnName("SnackBar_Id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("Order_Id");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.HasKey("SnackBarId", "ProductId", "OrderId");

                    b.HasIndex("ProductId", "SnackBarId");

                    b.HasIndex(new[] { "OrderId" }, "OrderDetailOfOrder_FK");

                    b.HasIndex(new[] { "SnackBarId", "ProductId" }, "OrderDetailOfProduct_FK");

                    b.ToTable("Order_Details", (string)null);
                });

            modelBuilder.Entity("AnVatCanTho.Models.Product", b =>
                {
                    b.Property<int>("SnackBarId")
                        .HasColumnType("int")
                        .HasColumnName("SnackBar_Id");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Description");

                    b.Property<string>("Ingredient")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Ingredient");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("ProductCategory_Id");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("Stock");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int")
                        .HasColumnName("UnitPrice");

                    b.HasKey("SnackBarId", "Id");

                    b.HasIndex(new[] { "SnackBarId", "Id" }, "PRODUCT_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "ProductCategoryId" }, "ProductOfProductCategory_FK");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductType_Id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "PRODUCT_CATEGORY_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "ProductTypeId" }, "ProductCategoryOfProductType_FK");

                    b.ToTable("Product_Categories", (string)null);
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductImage", b =>
                {
                    b.Property<string>("PathName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Path_Name");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<int>("SnackBarId")
                        .HasColumnType("int")
                        .HasColumnName("SnackBar_Id");

                    b.HasKey("PathName");

                    b.HasIndex("ProductId", "SnackBarId");

                    b.HasIndex(new[] { "PathName" }, "PRODUCT_IMAGE_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "SnackBarId", "ProductId" }, "ProductHasImage_FK");

                    b.ToTable("Product_Images", (string)null);
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "PRODUCT_TYPE_PK")
                        .IsUnique();

                    b.ToTable("Product_Types", (string)null);
                });

            modelBuilder.Entity("AnVatCanTho.Models.Rating", b =>
                {
                    b.Property<int>("SnackBarId")
                        .HasColumnType("int")
                        .HasColumnName("SnackBar_Id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    b.Property<double>("Star")
                        .HasColumnType("float")
                        .HasColumnName("Star");

                    b.HasKey("SnackBarId", "ProductId", "CustomerId");

                    b.HasIndex(new[] { "CustomerId" }, "DetailRatingOfCustomer_FK");

                    b.HasIndex(new[] { "ProductId", "SnackBarId" }, "DetailRatingofProduct_FK");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Name");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Permission");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "ROLE_PK")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AnVatCanTho.Models.SnackBar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Avatar")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Avatar");

                    b.Property<string>("CoverImage")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CoverImage");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Display_Name");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Password");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("Tel")
                        .IsFixedLength();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "SNACK_BAR_PK")
                        .IsUnique();

                    b.ToTable("Snack_Bars", (string)null);
                });

            modelBuilder.Entity("AnVatCanTho.Models.Ward", b =>
                {
                    b.Property<string>("DistrictName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("District_Name");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("DistrictName", "Name");

                    b.HasIndex(new[] { "DistrictName", "Name" }, "WARD_PK")
                        .IsUnique();

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Address", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.SnackBar", "SnackBar")
                        .WithMany("Addresses")
                        .HasForeignKey("SnackBarId");

                    b.HasOne("AnVatCanTho.Models.Ward", "Ward")
                        .WithMany("Addresses")
                        .HasForeignKey("WardName", "DistrictWardName")
                        .HasPrincipalKey("Name", "DistrictName");

                    b.Navigation("Customer");

                    b.Navigation("District");

                    b.Navigation("SnackBar");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Administrator", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Role", "Role")
                        .WithMany("Administrators")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Bill", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Order", "Order")
                        .WithMany("Bills")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Comment", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Customer", "Customer")
                        .WithMany("Comments")
                        .HasForeignKey("CustomerId");

                    b.HasOne("AnVatCanTho.Models.SnackBar", "SnackBar")
                        .WithMany()
                        .HasForeignKey("SnackBarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId", "SnackBarId")
                        .HasPrincipalKey("Id", "SnackBarId");

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("SnackBar");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Order", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AnVatCanTho.Models.OrderDetail", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.SnackBar", "SnackBar")
                        .WithMany()
                        .HasForeignKey("SnackBarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId", "SnackBarId")
                        .HasPrincipalKey("Id", "SnackBarId");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("SnackBar");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Product", b =>
                {
                    b.HasOne("AnVatCanTho.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.SnackBar", "SnackBar")
                        .WithMany("Products")
                        .HasForeignKey("SnackBarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("SnackBar");
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductCategory", b =>
                {
                    b.HasOne("AnVatCanTho.Models.ProductType", "ProductType")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductImage", b =>
                {
                    b.HasOne("AnVatCanTho.Models.SnackBar", "SnackBar")
                        .WithMany()
                        .HasForeignKey("SnackBarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId", "SnackBarId")
                        .HasPrincipalKey("Id", "SnackBarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SnackBar");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Rating", b =>
                {
                    b.HasOne("AnVatCanTho.Models.Customer", "Customer")
                        .WithMany("Ratings")
                        .HasForeignKey("CustomerId");

                    b.HasOne("AnVatCanTho.Models.SnackBar", "SnackBar")
                        .WithMany()
                        .HasForeignKey("SnackBarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnVatCanTho.Models.Product", "Product")
                        .WithMany("Ratings")
                        .HasForeignKey("ProductId", "SnackBarId")
                        .HasPrincipalKey("Id", "SnackBarId");

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("SnackBar");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Ward", b =>
                {
                    b.HasOne("AnVatCanTho.Models.District", "District")
                        .WithMany("Wards")
                        .HasForeignKey("DistrictName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Comments");

                    b.Navigation("Orders");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("AnVatCanTho.Models.District", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Order", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AnVatCanTho.Models.ProductType", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Role", b =>
                {
                    b.Navigation("Administrators");
                });

            modelBuilder.Entity("AnVatCanTho.Models.SnackBar", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("AnVatCanTho.Models.Ward", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
